### ISSUE TITLE
core_export_to_popolo_json command generates invalid organization ids

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#1515]
The `core_export_to_popolo_json` command generates organization ids with a leading `/` character. When trying to import that json it generates using the `core_import_popolo` the following error is produced:

```
Exception: The ID '/core_organisation/81' didn't match ^(?P<scheme>org.mysociety.za|myreps_id|myreps_person_id|za.gov.parliament)(?P<identifier>.*)$
```

Here's an example of an organization taken from http://www.pa.org.za/media_root/popolo_json/za-pombola.json

```json
{
  "category": "political",
  "classification": "Party",
  "contact_details": [],
  "id": "/core_organisation/81",
  "identifiers": [
    {
      "identifier": "/party/acdp",
      "scheme": "org.mysociety.za"
    }
  ],
  "name": "African Christian Democratic Party (ACDP)",
  "pa_url": "/organisation/acdp/",
  "slug": "acdp"
}
```

**Comment by geoffkilpin** [comment]
I have also encountered this issue (and it is probably something that should be addressed given that this import method is advertised at http://www.pa.org.za/help/api).

I've made a few simple changes at https://github.com/geoffkilpin/pombola/tree/fix-core-import-pombolo so that I can make use of this, but they are not merge ready and don't cover all issues. 

Points that I have not addressed properly (mostly covered by the hacks in the final commit):

* Setting of the preferred name for a person (if it is one of the alternative names)
* Importing of approximate dates - the import fails if a position starts on a date like '2014-06'
* Missing roles for positions
* Handling positions with no organisation id

**Comment by mhl** [comment]
@chrismytton and I looked into this more today.

Since creating the ticket, we've changed the IDs that are generated so that they don't have a leading `/` - they're all of the form `core_person:1234` or `core_organisation:2345`, where the number is the primary key in the corresponding table in Pombola.

However, core_import_popolo was never updated for that change. Really, it should now try to create people / organisations / positions with those IDs rather than slugs, so it needs quite a lot of changes.

On the broader issue of how we help people to get a development instance running, though, we're now publishing database dumps (e.g. http://www.pa.org.za/media_root/dumps/pg-dump.sql.gz ) which can be used (with a bit of fiddling - see #2029) to create a much closer mirror of the site.

So we're going to close this, and create tickets for updating the documentation to explain how to use the public database dump, and the documentation that suggests using core_import_popolo instead.

`core_import_popolo` should just be removed now, we think, since the database dumps are going to be much more useful.
