### ISSUE TITLE
Manual entry and scrapper

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/pombola#1575]
Hi please tell me what is possible with manual entry in app and what is with scrapper?
Tnks

**Comment by mhl** [comment]
Hi - essentially all data in Pombola can be edited in the Django admin interface, I think - similarly, you could programmatically import or update anything you like.

For this kind of general question, it would be better to contact [our international team](https://www.mysociety.org/mysociety-around-the-world/) rather than open a GitHub issue.
