### ISSUE TITLE
ZA: show more page indices in pagination links

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1652]
(Raised by PMG: this at least applies to committee appearances and blog posts.)

![pagination-1](https://cloud.githubusercontent.com/assets/7907/7185703/49b2e312-e45c-11e4-9f0c-8c2360c46908.png)

![pagination-2](https://cloud.githubusercontent.com/assets/7907/7185704/4c13f0c4-e45c-11e4-8a8a-d85a31ee350d.png)

In both these cases, they'd like more indices (at least 4 at the start and end, I guess) in the pagination links.

**Comment by lizconlan** [comment]
So the first example is using the default `paginate` tag which we can alter by setting `PAGINATION_DEFAULT_WINDOW` to a larger number in the country specific settings file (is defaulted to 2 in the main settings.py file). The tricky bit would be doing it so that the expanded pagination bar doesn't split as it runs out of width.

The second is a bit trickier as django-paginate isn't good at recognising custom template files (or I'm not good at working out how to make it do so, open to "hey, just edit this and it works!") so we'd have to write something to fake the `context['pages']` bit of django-paginate's `paginate` template tag.
