### ISSUE TITLE
Redesign of the pa.org.za homepage

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1670]

**Comment by paullenz** [comment]
Wireframe in the first instance - very rough first pass done by dave_w when in ZA show below.

+ some notes:  


1. The curated issue pages we have to put on hold as a possible phase 2 as we do not have the HR currently
Could we replace the 6 buttons with the topics below:
 
Middle 6 buttons:  MP comments* / MP Corner / Minister's Replies to MPs / MP Attendance / MP Assets / Activist Campaigns
* Could one have a search button that takes you to a dedicated page showing just the MP's Committee and Plenary comments? These appearances would still remain as well on the MP's profile page but it would be a way to surface another part of the website, Appearances, that is pure technical wizardry.

![pa-mockups 001](https://cloud.githubusercontent.com/assets/909811/8282617/e44a66d6-18e9-11e5-816b-cce5807c3c79.png)

**Comment by zarino** [comment]
New homepage layout, retaining the current PA style:

![homepage - wide](https://cloud.githubusercontent.com/assets/739624/8356477/7a372b9c-1b4d-11e5-9e59-ae6b464a4101.png)

(This is what it might look like on a narrow screen:)

![homepage - narrow](https://cloud.githubusercontent.com/assets/739624/8356480/83127686-1b4d-11e5-88bb-63a66f026efd.png)

Here it is in full green, although I'd suggest against it for two reasons:

* It's harder to differentiate between normal text and links, since, aside from white, not very many colours work well on dark green.
* Maybe it's just me, but it feels quite oppressive. Something to test with local users maybe?

![homepage - wide dark](https://cloud.githubusercontent.com/assets/739624/8356582/1b0e1634-1b4e-11e5-9274-915ef4c51a5f.png)

If they *really* want the green, but agree a full green background is too much, we could always tweak the existing style to make green the primary accent colour:

![homepage - wide light](https://cloud.githubusercontent.com/assets/739624/8356621/66ab4d64-1b4e-11e5-89ae-be628cbc964e.png)

That's only a really quick mockup – we'd probably work a little harder on getting the colours right, but it gives you an idea.

**Comment by davewhiteland** [comment]
Awaiting feedback (@paullenz emailed wireframes): PMG said they like them :-) and that Zaheedah is handling this but has been away (2-Jul-15), so expect followup soon...

**Comment by wrightmartin** [comment]
![homepage - wide light copy 4](https://cloud.githubusercontent.com/assets/2292925/9040760/100576ca-39fc-11e5-95b5-3c4629257886.png)

**Comment by zarino** [comment]
A potential tweak to @wrightmartin’s mockup above, except with the middle section lightened up a bit.

This has the dual benefits of making the search box and newsletter signup a lot more prominent, and also making the content of the infographics stand out better:

![homepage - wide light copy 4](https://cloud.githubusercontent.com/assets/739624/9229610/d7e12728-4115-11e5-955e-506bbec47b20.png)

We should get feedback from PMG, but for my money, I'd say this is pretty ideal.

**Comment by zarino** [comment]
I've started work on this in the [1670-za-homepage-redesign branch](https://github.com/mysociety/pombola/compare/1670-za-homepage-redesign)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/pombola/pull/1727

**Comment by Gemmamysoc** [comment]
Megan's feedback:

Here are some minor suggestions to make the infographics show more at the bottom of the screen:

Currently, most people's pc resolutions (zoom) are set to about 90% or 100% and the homepage then ends just under the broad green band and there is really no indication that they could scroll down and see the infographics or 'hot topics' tabs at the bottom of the page. The result looks a bit 'text heavy'. Is it possible to shorten the green band containing “contact your representative/stay up to date”? We could lose “see how they could help” and include that on the next page once they have used the Rep Locator.

We would also like to see how the three articles would look using a slightly smaller font, and perhaps cut off the text after four lines instead of five lines. The aim is to have a partial or full view of the infographics when opening the home page. 

For example:

LATEST NEWS Show more news

Infographic: The Fifth Parliament 2015 - First Term Review

April 2, 2015

With the first term of Parliament done
and dusted, the People’s Assembly takes a look at
some of the Legislature’s activities from this
period… More

Thanks!

**Comment by wrightmartin** [comment]
> most people's pc resolutions (zoom) are set to about 90% or 100% and the homepage then ends just under the broad green band and there is really no indication that they could scroll down and see the infographics or 'hot topics' tabs at the bottom of the page

The size of most people's screens is a bit of a moving target and varies wildly. We'll need to take a look at Google Analytics data to get an idea of how many people may be affected by this. If we move the section up or down it will only solve the problem for a few users, and might cause it for others. It's a tricky one that affects every website on the internet.

**Comment by zarino** [comment]
So, on "desktop width" windows/devices, the green bar finishes about 650px down the page, then there's the infographic section header, and the very top edge of the tallest infographic is 750px down the page. Ideally you'd want a window at least 850px high, to see the top 100px of the infographic images.

Some quick calculations based on visitor *screen* dimensions from Google Analytics – considering only visitors from the last 6 months, with a screen width of 768px or greater, and deducting 150px from the screen height to simulate a typical window height (ie: -150px for browser chrome, OS menu bars, task bars etc)…

* 53% of visitors would see beyond the green bar (window at least 650px high)
* 43% of visitors would see the infographic header (window at least 750px high)
* 28% of visitors would see the tops of the infographics (window at least 850px high)

This is all very back-of-the-envelope, but it's not hard to imagine that shaving 100px off the elements above the infographics, would potentially double the number of people who'll be able to see the infographics above the fold.

**Comment by zarino** [comment]
Oh, except I missed that we'd already thought a bit about this, and put in some media queries that reduce vertical padding when the screen is short, so it's not quite as bad as I previously estimated. Still, we can improve it a bit.

**Comment by zarino** [comment]
Here's a PR for some simple changes to the homepage media queries, to make sure more of each infographic is visible on screens in the 600–800px height band:

https://github.com/mysociety/pombola/pull/1753
