### ISSUE TITLE
Investigate the replacement of Disqus with Facebook comments on pa.org.za

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1676]
Set up on a dev server to see what it looks like?  It looks pretty straightforward (to a non-technical person)

https://developers.facebook.com/docs/plugins/comments

**Comment by lizconlan** [comment]
While I understand the attraction of a ready-made audience, on balance I don't think that using Facebook for comments is going to prove successful, especially in the longer term.

Facebook comments can only be contributed by people with a Facebook account and not everybody who may wish to add a comment has or wants one (alas, Facebook used to allow third party logins for the comment plugin, but [this useful feature was withdrawn in the previous version of the API](https://developers.facebook.com/docs/plugins/comments#third-party-login)). Disqus, on the other hand, can be configured to use many login providers, including Facebook (which is how I believe is one of the options currently available on the www.pa.org.za site).

I found using the Facebook API really difficult as it is not well documented and many of the helpful articles on the internet are out of date, which strikes me as a worrying sign. This will make it hard for us to make any changes to the site involving comments or to change how the comments work in any way. I also got the feeling that any feature we came to rely on might be withdrawn or changed beyond recognition at any moment - a lot of what I saw on Stack Overflow was people posting "hey, this worked last week - how do I fix it?".

Switching to Facebook will mean that they are in control of the comment data and functionality, which could prove problematic both in terms of ownership and functionality. At present, it is tricky, although technically possible to export the data for backup purposes (although questions remain about whether we'd be able to get all of it as some reports suggest that their pagination system is either broken or unreliable). And Facebook do not have a good track record for taking great care with their users' data or privacy preferences.

Disqus provide a much richer and more stable API - this is their main business after all, if they break their core service, that will be bad for them as well as us.

And lastly, if we did switch, I can't see how we would retain the comments from the previous system other than of closing all the discussion threads to new content and providing a link to an archive page; there's means to import them into Facebook's system.

**Comment by paullenz** [comment]
So I appreciate the reasons against, but the reality is that the almost no
one uses the existing disqus comments - and the feedback that we got from
users was that they are more likely to use FB

FB penetration amongst Internet users in South Africa is over 50% -
http://techcrunch.com/2014/09/08/facebook-africa/ can we at least try
getting up an FB comments version on staging for the local team to review
and share for feedback?


On 22 Jul 2015, at 22:16, Liz Conlan <notifications@github.com> wrote:

While I understand the attraction of a ready-made audience, on balance I
don't think that using Facebook for comments is going to prove successful,
especially in the longer term.

Facebook comments can only be contributed by people with a Facebook account
and not everybody who may wish to add a comment has or wants one (alas,
Facebook used to allow third party logins for the comment plugin, but this
useful feature was withdrawn in the previous version of the API
<https://developers.facebook.com/docs/plugins/comments#third-party-login>).
Disqus, on the other hand, can be configured to use many login providers,
including Facebook (which is how I believe is one of the options currently
available on the www.pa.org.za site).

I found using the Facebook API really difficult as it is not well
documented and many of the helpful articles on the internet are out of
date, which strikes me as a worrying sign. This will make it hard for us to
make any changes to the site involving comments or to change how the
comments work in any way. I also got the feeling that any feature we came
to rely on might be withdrawn or changed beyond recognition at any moment -
a lot of what I saw on Stack Overflow was people posting "hey, this worked
last week - how do I fix it?".

Switching to Facebook will mean that they are in control of the comment
data and functionality, which could prove problematic both in terms of
ownership and functionality. At present, it is tricky, although technically
possible to export the data for backup purposes (although questions remain
about whether we'd be able to get all of it as some reports suggest that
their pagination system is either broken or unreliable). And Facebook do
not have a good track record for taking great care with their users' data
or privacy preferences.

Disqus provide a much richer and more stable API - this is their main
business after all, if they break their core service, that will be bad for
them as well as us.

And lastly, if we did switch, I can't see how we would retain the comments
from the previous system other than of closing all the discussion threads
to new content and providing a link to an archive page; there's means to
import them into Facebook's system.

—
Reply to this email directly or view it on GitHub
<https://github.com/mysociety/pombola/issues/1676#issuecomment-123866946>.

**Comment by JenMysoc** [comment]
I second Paul's comments. We know from talking to partners that in the majority of african countries we're working in, Facebook is the natural medium to comment and communicate. This is possibly due to it being offered for free on a number of mobile phones so people don't have to use data or credit to communicate

**Comment by dracos** [comment]
They won't be on Facebook though. This is commenting provided by Facebook, not on Facebook; I've not seen a nice use of it. Personally, I think if no-one is really using the Disqus comments, probably no-one will use Facebook comments either; the issue is not wanting to comment, not which platform provides comments (so the easy solution is turning them off, and letting people comment on things within Facebook as they probably already are doing anyway if they want, unless we magically think Facebook comments will be of high quality). But if it's just one line of JavaScript and we don't put any effort into it and don't really care how the comments section appears or getting information about them, it's just a thing to have, then it doesn't really matter.

**Comment by wrightmartin** [comment]
What kind of filesize do either of these add? If no-one is commenting should we be impacting the site performance negatively at all – a slower site will do more to deter visitors than either of these comment solutions will add

**Comment by dracos** [comment]
They both load async, and appear at the bottom of e.g. a blog post, so I don't think that will matter too much, though obviously greater than zero.

**Comment by lizconlan** [comment]
It's more than just a line of javascript, there's a whole load of setup cruft as well - not much page weight but a surprising amount of messing around to be done with the site code.

It is noticeable on Facebook's own example page that the way they've embedded a comments forum breaks in-page linking (at least until the whole page is in the browser cache) as the comments block suddenly jumps in and pushes everything down \*sigh\*

**Comment by JenMysoc** [comment]
@paullenz is there anything from the user design research you did that implies that people will comment if the commenting platform is moved to facebook? We're hypothesising that people won't comment no matter what we do and we're also hypothesising that people will comment if we move to facebook comments. 

We know there's a large facebook userbase already so what we need to understand is if there's an appetite for commenting on political sites using facebook, if there is then the desire of PMG to have this feature coupled with an appetite for political discussion using facebook comments might push it more towards being worth it.  

Maybe @paullenz could give some tips, possibly from Code4SA, on websites that can demonstrate an appetite for facebook comment discussion?

**Comment by lizconlan** [comment]
Oh and one thing I missed in my writeup - Facebook make it super hard to work out how to do any kind of reporting or other API footling with comments made against a plugin, I found out how to do it by accident (you have to look up the ID of the comment thread using the page url you've set it to work with as a key then write your API calls against the ID you just found). It feels really fragile, in a not-even-sure-this-is-supposed-to-be-a-thing way, so would hate to rely on it for anything.

**Comment by dracos** [comment]
@lizconlan To have it at its most basic, if you didn't care about reporting or anything (do we care about reporting?), it appears to be the FB loading code in the "header" (start of body) and a line where you want the comments to be; there already is a separate comments template already, so that looks straightforward. And Disqus does the comment block jumping the page too, that's not new (there's a comment in the code saying that's why the Disqus is so low, in fact).

**Comment by lizconlan** [comment]
@dracos there's a ticket for reporting (referenced above), so presumably we care about reporting. So either we'd have to have 2 sets or reporting code to look after or not have reporting for ZA. But yes, FB loading code high up in the body's header section, a new meta tag in the html head section and a line where the comments should be with some new magic so that we have a unique string per comment thread (as opposed to page if we want the same thread to appear on multiple pages, but I might have imagined that). Also an FB app id.

**Comment by paullenz** [comment]
So @steiny created the reporting ticket - it would only be something we cared about if there was a Pombola site that wasn't hitting traffic targets but was, by dint of comments, hitting the transactions target.  That certainly isn't the case for pa, as it is hitting traffic, nor Mzalendo and the other pombola sites don't fall into the latter camp, so it really isn't a priority
