### ISSUE TITLE
Redesign of person page on pa.org.za

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1680]
Wire framing for now - rough first pass from dave_w below:

![pa-mockups 003](https://cloud.githubusercontent.com/assets/909811/8283846/a7525768-18f1-11e5-8e85-d5a7ef714bc8.png)

**Comment by mhl** [comment]
Could you or @davewhiteland possibly add some notes here about what the important differences are here from the pages at the moment, for reference of the designers / developers working on it? (e.g. I see that the contact addresses are much more prominent, as is the Register of Interests.)

**Comment by davewhiteland** [comment]
@mhl yup, we (@paullenz and @davewhiteland) have a call with @zarino tomorrow (wed 24) to discuss and as part of that I'll add notes here too

**Comment by zarino** [comment]
Here's the new layout, in the current PA style:

![mp page - wide](https://cloud.githubusercontent.com/assets/739624/8356760/2abb622a-1b4f-11e5-8806-502a45540df7.png)

(And here's how it'd look on a narrow screen:)

![mp page - narrow](https://cloud.githubusercontent.com/assets/739624/8356761/2d1e0964-1b4f-11e5-86c2-486061a817ea.png)

Here's how it would look on a dark green background, although, as with #1670, I'd recommend against it for two reasons:

* It's harder to differentiate between normal text and links, since, aside from white, not very many colours work well on dark green.
* Maybe it's just me, but it feels quite oppressive. Something to test with local users maybe?

![mp page - wide dark](https://cloud.githubusercontent.com/assets/739624/8356765/31ea5092-1b4f-11e5-9918-6304d2a4157c.png)

If they really want the green, but agree a full green background is too much, we could always tweak the existing style to make green the primary accent colour:

![mp page - wide light](https://cloud.githubusercontent.com/assets/739624/8356768/36905448-1b4f-11e5-8210-fdb7d74a3c69.png)

(Colours in that shot need some work, but it gives you the idea)

**Comment by davewhiteland** [comment]
Awaiting feedback (@paullenz emailed wireframes): PMG said they like them :-) and that Zaheedah is handling this but has been away (2-Jul-15), so expect followup soon...
