### ISSUE TITLE
Add link under "democracy resources" on ShineYourEye

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1695]
Add a drop-down link to "Resource Files" - link to follow

**Comment by lizconlan** [comment]
@paullenz is the link available yet?

**Comment by paullenz** [comment]
This one - but 404ing for some reason?  Created on the admin interface

**Comment by mhl** [comment]
I think @paullenz meant to include this link: http://www.shineyoureye.org/info/resource-files

It's producing a 500 error at the moment, which is caused by having an empty page - I've made a pull request here:

* https://github.com/mysociety/pombola/pull/1749

Perhaps @lizconlan or @duncanparkes could deal with that PR next week, and also make the menu change?

**Comment by mhl** [comment]
I think this is done now, but there's nothing on the page at the moment - as I understand it that's for the team in Nigeria to populate.
