### ISSUE TITLE
Mzalendo 2013 Data corrections 

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1712]
@duncanparkes @paullenz @mhl 

I. Emma Getrude a nominated Senator has two existing profiles, Kindly merge the two.
a)http://info.mzalendo.com/person/emma-mbura-gertrude/
b)http://info.mzalendo.com/person/emma-mbura-getrude/

2. Aaron Rotich Tuikong's speech entries should be moved to Hon Mary Emaase's profile. Rotich is not a member of parliament. 

3. The speech entries on Josephat Nanok's profile from March 2013 should be moved to Daniel Epuyo Nanok's profile.

4. The speech entries on Eric Opon Nyamunga's profile from March 2013 should be moved to Rose Auma Ogendo's profile.

5. The speech counts under James Mungai Njoroge should be moved to Nakuru's Senator profile James Kiarie Mungai. James Mungai Njoroge erroneously appears as a Member of Parliament. 

6. The speech counts under Rachael Nduku Ndambuki should be put under Rachael Kaki Nyamai. Rachael Nduku Ndambuki is not a member of parliament.

**Comment by lizconlan** [comment]
Hmm, this is tricker than I initially realised - need a script to cover the following cases:

- [ ] move all speech entries associated with a Person A to Person B then (optionally) delete Person A's details
- [ ] move a subset of speech entries from Person A to Person B

(does anything else need to happen to regenerate/reindex/fix caching?)

**Comment by mhl** [comment]
The Emma Getrude case should be dealt with by core_merge_people, but @lizconlan reported that it wasn't merging the hansard entries, although there is code for that in the comment - that needs to be investigated and fixed.

While we're doing this ticket, it would be good to make two changes to the core_merge_people command:
* Ask for keyboard confirmation that the two people should be merged (since if you input their IDs only, it's worrying without a confirmation including their real names)
* Possibly also allow slugs to be specified instead of IDs

For moving the speeches, I think it would be good to have a new command for doing this, which, as @lizconlan points out, should have optional start and end date options to restrict it to a time period.

We discussed this and it would be worth clarifying whether Rachael Nduku Ndambuki should be in the database still.

Finally, I assume that the final step of this ticket is to regenerate gender data that @duncanparkes produced for Mzalendo.

**Comment by lizconlan** [comment]
if I've read the original text correctly, we should also clarify whether James Mungai Njoroge and Aaron Rotich Tuikong should remain in the database
