### ISSUE TITLE
Data added in May via admin interface not showing [NG]

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1716]
Data that has been added in May is not showing on ShineYourEye

This data was MP profile data and is added via the admin interface. 

PROFILE UPLOAD (for MP)
Done on the admin end of the site
Data included - name, sex, political party, picture, state, senatorial district...

According to our partners up to 109 records were added - some are showing (in the region of 88) but many others aren't.

**Comment by JenMysoc** [comment]
People they've added that aren't showing:

1. Suleiman Hunkuyi
2. Jibrin Barau
3. Bayero Nafada
4. Mohammed Hasan
5. Umaru Kurfi

**Comment by mhl** [comment]
@duncanparkes, @lizconlan and I looked into this a bit further - I'm afraid we can find no trace in the admin log of these people being created in May. Our best guess is that for these cases either:

1. there were network problems at the point of saving or
2. the person entering the data forgot to click save.

It might easily be 2, since the admin interface doesn't produce an "Are you sure you want to leave this page?" Javascript warning if you try to close the form before it's saved. This might be a good feature to add, so I've created an issue for that: https://github.com/mysociety/pombola/issues/1732
