### ISSUE TITLE
front-end performance sprint

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1764]
The idea of this is to spend a few days (Monday 21st of September to Wednesday 23rd of September) working with @wrightmartin and / or @zarino to focus on getting down page-load times for Pombola sites, and look at ways we could improve the experience for people using the site by reducing asset sizes, changing load order, using image sprites, etc.

It would also be a good chance to look at questions like "is it still worth using Modernizr?", related to https://github.com/mysociety/pombola/issues/1686

**Comment by wrightmartin** [comment]
- Shall we give ourselves a target? Say ~10% of requests, ~20% filesize?
- We shouldn't worry about any of the more difficult optimisations (critical path rendering etc) until we've taken care of the low hanging fruit
- We should make this process as repeatable as is sensible, so we could do it at regular intervals (every year?) and apply it to all of our sites.
- We should draw up rough guidelines for new projects, so that we always start from a performant place

**Comment by wrightmartin** [comment]
### Pombola specific
- [ ] Ensure we're only loading CSS and JS that is used for the current domain (Eg. no mzalendo assets loading on People's Assembly) 
- [ ] Ensure we're only loading assets of 'one-off' pages on the page they are needed for (Eg. Mzalendo women's page)
- [ ] Look at jQuery dependencies - try and use native JS if possible
- [ ] Consider replacing or removing social media plugins

### General performance enhancements
- [ ] Combine and gzip all JS files
- [ ] Image compression
- [ ] Ensure images are rendered at the size they are required (could use ```srcset``` for this)
- [ ] Minimise requests
- [ ] Use sprites for CSS images

**Comment by wrightmartin** [comment]
### Mzalendo

Homepage
![screen shot 2015-09-21 at 09 04 49](https://cloud.githubusercontent.com/assets/2292925/9987455/e8580b0a-603f-11e5-928e-d8816b39fe0d.png)

Person page
![screen shot 2015-09-21 at 09 05 06](https://cloud.githubusercontent.com/assets/2292925/9987457/ed6008dc-603f-11e5-9447-1719b3705608.png)

**Comment by wrightmartin** [comment]
People's Assembly

Homepage
![screen shot 2015-09-21 at 09 06 06](https://cloud.githubusercontent.com/assets/2292925/9987482/216e71fe-6040-11e5-9705-66278ae90160.png)


Person page
![screen shot 2015-09-21 at 09 07 23](https://cloud.githubusercontent.com/assets/2292925/9987487/34246740-6040-11e5-8fb3-7131393ba350.png)

**Comment by wrightmartin** [comment]
### ShineYourEye

Homepage
![screen shot 2015-09-21 at 09 08 27](https://cloud.githubusercontent.com/assets/2292925/9987503/6133fc3c-6040-11e5-8ad0-c9d82aa11437.png)

Person page
![screen shot 2015-09-21 at 09 09 12](https://cloud.githubusercontent.com/assets/2292925/9987516/77ceb798-6040-11e5-8528-840048980353.png)

**Comment by dracos** [comment]
For interest, as I had a look, mobile width, ignoring the 300Kb ish Twitter timeline (as that's below the fold, perhaps it could somehow  only load if you're scrolling down to it…? Or proxy it to remove the images I guess), I make the Mzalendo front page 224Kb, of which:
* 131Kb images (of which parliament image is 104Kb)
* 33Kb jQuery
* 23Kb Google feeds JavaScript (for latest news; aside would be good if it could link to the blog rather than just say "Loading news…")
* 21Kb CSS
* 11Kb site JavaScript (5Kb countdown script) (looks like the "both" JS could be got rid of with not much work since Django 1.5! :) )
* 5Kb page

So 50Kb without JS, 100Kb with JS, looks achievable. And a hard challenge would be something like 20Kb/50Kb? ;)

**Comment by wrightmartin** [comment]
# Post sprint measurements

### PA
Homepage
<img width="583" alt="screen shot 2015-09-28 at 10 18 58" src="https://cloud.githubusercontent.com/assets/2292925/10131727/5ce58a58-65ca-11e5-92b2-837170ea5b51.png">
