### ISSUE TITLE
ZA - search button off by one pixel

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1843]
You can see here that the search button, for me at least, is slightly lower than the search box it is next to

![2015-11-26-150238_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/11425772/3bceef90-944f-11e5-9392-57be64ff5488.png)

**Comment by zarino** [comment]
Looks like a CSS `vertical-align` issue to me. I can't replicate it on Chrome on my Mac, so maybe it’s a Linux thing?

![screen shot 2016-02-05 at 16 27 52](https://cloud.githubusercontent.com/assets/739624/12852140/6ec5f502-cc25-11e5-86d9-27f82773528e.png)

Technically, the two inputs should use the `vertical-align: baseline` from their parent. If that doesn’t work, we could belt-and-braces it, and see whether adding something like `vertical-align: bottom;` to the styles for `.inline-search-box` fixes it on Duncan’s computer.

**Comment by paullenz** [comment]
Safari for Mac as well:

https://www.dropbox.com/s/4sokxdzjpqxloov/Screenshot%202016-02-05%2016.32.37.png?dl=0

**Comment by zarino** [comment]
Whoa, turns out I was wrong. It's not vertical alignment. In Safari, at least, it's because the submit button has `margin-top: 2px; margin-bottom: 2px` – and as far as I can tell, that's not being set by us, it’s coming from the browser’s default styles.

So I have a feeling, just adding `margin: 0` to `.inline-search-box .button` should fix it.
