### ISSUE TITLE
ZA Rep Locator - including ward councillor information

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1895]
Currently the rep locator - http://www.pa.org.za/search/location/ only includes national level reps

The councillor search - http://www.pa.org.za/ward-councillor-lookup/ is a separate widget created by Code for South Africa

We would like a single search to return all reps on a lovely, easy to understand page, probably using data from the C4SA API

Related tickets:

https://github.com/mysociety/pombola/issues/1315

https://github.com/mysociety/pombola/issues/1883

**Comment by zarino** [comment]
These mockups came out of a call we had with PMG last week. We've sent them to PMG, and they had some feedback:

* Doesn't make sense to split "MPs" from "MPLs" – just combine them in one list
* The MP+MPLs tab should be shown first, rather than Councillors

![councillors](https://cloud.githubusercontent.com/assets/739624/12548948/bb2d58cc-c351-11e5-980f-3edb69082328.png)

![mps](https://cloud.githubusercontent.com/assets/739624/12548949/bddc7a3a-c351-11e5-8c20-f55deb605049.png)

**Comment by tmtmtmtm** [comment]
@zarino how much design time is required to actually implement this now?

**Comment by zarino** [comment]
@tmtmtmtm: About 1 day. I could either do it as static HTML+styling before a developer wires it up with real data, or I could do it after a developer has created the template that provides the data I'd need.

**Comment by mhl** [comment]
The 1895-new-rep-locator branch is probably enough for @zarino to start working on this. Some questions came up as I was doing it, though:
* Since those redesigns don't include the "National Level Politicians" view, I've removed it. It didn't seem useful anyway, since I think it just showed all politicians associated with the province, regardless of the distance of their office. A quick look at analytics suggested to me that it wasn't much used anyway.
* If we're just having a single tab for both MPs + MPLs, it seems strange to me to have two tabs at all, since the first one (ward councillors) will only ever have 1 person on it anyway. So I just put a heading in front of the ward councillor and heading introducing the MPs + MPLs. Obviously it's easy to change to tabs again.
* As well as MPs / MPLs, we also have people in the database who are constituency contacts who aren't MPs or MPLs according to our records. I've included them anyway, but maybe PMG would rather they weren't included. (They will appear on the constituency office / constituency area page anyway, if someone clicks through.)
* I'm not sure what to do about the contact details. There might be email, postal address and phone number associated with the person as well as associated with the constituency office / constituency area. Do we want to show all of these on the results page? I'm inclined to think that the constituency office pages present all this nicely at the moment, so maybe we should be encouraging people to click through to that rather than trying to figure out how show two email addresses (say) for a person on the results page in a clear way.
* This does too many queries at the moment, but let's figure out the desired implementation and then reduce that with `select_related` / `prefetch_related` rather than cluttering the code with them at this stage.

**Comment by zarino** [comment]
Ok, as of https://github.com/mysociety/pombola/commit/b3417330dc9afcf2f3e691d398867ae4380b8951, it looks like this:

![screen shot 2016-02-26 at 15 44 24](https://cloud.githubusercontent.com/assets/739624/13356956/f336a1c6-dc9f-11e5-93f6-91c8e74d02d4.png)

Things that still need work:

* What do we do about "DA Constituency Areas" (ie: the DA alternative to constituency offices). Technically they don't have a fixed street address, so how do we display them in the results list?
* There used to be an "About Constituency Offices" link on this page – do we still need it?
* The mockup included a paragraph above the results list, explaining what an MP / MPL / Councillor is, and what sorts of things you should talk to them about. Do we still want this? And if so, what text should we use?
* The nouns in the tabs ("MPs", "MPLs", "Councillors") need to be correctly pluralised – unless we can guarantee that every possible location will always be served by more than 1 MP or MPL, and exactly one Councillor?
* The map needs to zoom in closer when you switch to the Councillor tab, to show your ward in more detail. (I think @mhl is working on this as I speak.)

**Comment by mhl** [comment]
A first version is on staging now for feedback from PMG: http://za-pombola.staging.mysociety.org/place/latlon/-33.924,18.449/?q=church%20hill%2C%20cape%20town#mps

(You may need to force reload to make sure you get up-to-date CSS.)

**Comment by duncanparkes** [comment]
Feedback from Megan

  [ ] When clicking on the option to see the 14 more MPs, there is not an option to revert back to the original 10 (show less option).
  [ ]  Show the following extra data: Name of Ward, Name of Municipality, Municipality Website, Municipality Phone Number, and Party Contact Details

**Comment by duncanparkes** [comment]
Also needed:

  - [ ] Change 'Hot Topics' to point to the rep locator.
  - [ ] Redirect the old url to the right place.

**Comment by zarino** [comment]
> there is not an option to revert back to the original 10 (show less option).

Why do we need a "show less" option?

> Show the following extra data: Name of Ward, Name of Municipality, Municipality Website, Municipality Phone Number, and Party Contact Details

Surely you mean on some other page? There is no way we can display all of this information *for every single representative* without sacrificing the simplicity and legibility of the page.

I worry we've been bikeshedding this ticket for so long that we've forgotten its core purpose: **Showing who represents you.** You put in your location, you get a list of people. It's not meant to be the *entire contents* of Peoples Assembly on one single page.

Or have I misunderstood? /cc @mhl @JenMysoc

**Comment by duncanparkes** [comment]
Ward councillor url redirect: e8768af9ae9cbb207aff5c5b7ab2277a9c749594
Remove councillor lookup from Hot Topics: 132cdba2277b792140f69cd81e8c5a2a37ca0373

**Comment by JenMysoc** [comment]
@zarino apologies I had an email in my drafts about this which is now sent - thought it went last week.

**Comment by duncanparkes** [comment]
Fixed in d6680cc471791896acb7bed8b5d2ec4937bd0946.
