### ISSUE TITLE
[NG] Implement their homepage design on SYE

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1910]
EiE have had a homepage designed for them by Paschal from their team. They would like this implemented on their site.

The design is here: http://www.eie.ng/syedemo/ 

![screen shot 2016-01-19 at 13 11 55](https://cloud.githubusercontent.com/assets/739624/12419499/644b2c16-beae-11e5-9934-111cb34a99af.png)

@zarino and @wrightmartin what do we need to do this? Is this something that you would prefer to re-make yourselves or shall I ask Paschal to make any final changes and then get something sent to us? If we go this latter route what does it need to be that they send us?

**Comment by zarino** [comment]
Given that this needs to work as part of the existing framework of the site, it's probably best if they just get it *looking* how they want it to look (whether that's static image mockups, or a prototype webpage), and then @wrightmartin or I actually implement it as custom templates inside of Pombola (which will, in reality, mean writing it mostly from scratch, but the end result is that they'll have a homepage that looks as close as possible to what they give us).

This doesn't look like a particularly complex layout to implement in Pombola. I expect it will take no more time than the "Women Representatives" on Mzalendo took at the end of last year.

The design they have so far looks good to me! My only observation is that we'll need to add a standard navigation bar in somewhere, probably near the top. Since, once you're on a page *other* than the homepage, you'll need a way to navigate to the other sections like "News", "Events", and Search.

**Comment by JenMysoc** [comment]
![sye mock-up](https://cloud.githubusercontent.com/assets/4170351/13046307/ff375598-d3cf-11e5-8157-cb48e51c1414.jpg)

is the final signed off design!

**Comment by wrightmartin** [comment]
@JenMysoc thanks - is this going to be Pombola or Pombola simple?

**Comment by JenMysoc** [comment]
SO, that's up for debate.

They want a pombola simple by June (as per #1914); maybe it's just worth
doing it now? We were planning on rolling it out slower.

On 15 February 2016 at 10:54, Martin Wright <notifications@github.com>
wrote:

> @JenMysoc <https://github.com/JenMysoc> thanks - is this going to be
> Pombola or Pombola simple?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/pombola/issues/1910#issuecomment-184165611>.
>



-- 
Jen Bramley
*International Project Development Manager*
mySociety | mysociety.org/
Tel: 0044 (0) 7806 604 041
Skype: JenMySoc
@mySocietyIntl

If you have set up Alaveteli or FixMyStreet please fill in our surveys!
FixMyStreet Survey
<https://docs.google.com/forms/d/10PnEmAgX9d3ZayB2O9xGKNbGaBWaPK9ioSs-rz4-SgM/viewform>
 and Alaveteli Survey
<https://docs.google.com/forms/d/1INYP6NUOukNWXhzHDWCGlxySE0_LibMaa1zqma_kuRc/viewform>

**Comment by tmtmtmtm** [comment]
I think the best approach is to do a spike on how quickly we can migrate the site as a whole to Pombola-simple. If we could do the entire migration this sprint, then I think we should go for it, and do the design within that. If not, then we need to see whether we can end up with a hybrid, with some across each, or whether we just do the design within Pombola for now, and then migrate it again later.
