### ISSUE TITLE
[KE] MP speeches data not capturing all MPs

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1922]
Certain MPs appear not to have been captured for Jessica's MP Speeches data, these are

Judah Katoo Metito - the MP of Kajiado East
Christopher Omulele - the MP of Luanda Constituency in Vihiga County. 
John Zebedeo opore - the MP of Bonchari in Kisii County. 
Kipkorir Marisin Sang - the MP of Bureti in Kericho County.

These people should all be on the list, even if they have not spoken (see ticket #1917 )

**Comment by duncanparkes** [comment]
I've looked through the data to see why each of these people wasn't appearing.

Judah Katoo Metito (http://info.mzalendo.com/person/judah-ole-metito/)
 - didn't have a memberships of the Parliament, just a coalition membership with NA membership as a subtitle. I've added a membership of Parliament with the 'Member of the National Assembly' membership title, and cleared the subtitle on the coalition membership.

Christopher Omulele (http://info.mzalendo.com/person/christopher-omulele/)
 - There was a membership with the right membership title, but it was of an organisation called National Assembly, rather than of Parliament. I've changed it to point at Parliament instead.
We should check all memberships on the National Assembly organisation and make sure they're correct.

John Zebedeo Opore (http://info.mzalendo.com/person/john-opore/experience/)
 - Didn't have any current membership of Parliament, so I've added one. Note that there are now two people listed as members of the Bonchari. Is the other erroneous? http://info.mzalendo.com/place/bonchari-2013/

Kipkorir Marisin Sang (http://info.mzalendo.com/person/kipkorir-sang/)
- Didn't have any current membership of Parliament, so I've added one. Note that there are now two people listed as members of Bureti. Is the other erroneous?
http://info.mzalendo.com/place/bureti-2013/

**Comment by tmtmtmtm** [comment]
According to https://en.wikipedia.org/wiki/11th_Parliament_of_Kenya, John Zebedeo Opore _was_ the MP for Bonchari until 2 October 2013, when he was replaced by John Oroo Oyioka.

Also, according to https://en.wikipedia.org/wiki/Bureti_Constituency, Kipkorir Marisin Sang was the old MP for Bureti until 2007, when he was replaced by Franklin Bett, and *Leonard* Sang is the current MP.

**Comment by duncanparkes** [comment]
Thanks @tmtmtmtm. I've removed the two memberships that I created there for John Zebedeo Opore and Kipkorir Marisin Sang, as I'm pretty sure you're correct.

**Comment by mhl** [comment]
These have all been fixed now.
