### ISSUE TITLE
[KE] Speech counts appearing for people who aren't politicians on MP data for Jessica

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1923]
This appears to be happening in a couple of places and usually where someone has been a part of the last election. Examples of this are:

Maalim Mohamed Abdisalan - he is not a member of Parliament but he has speech counts the data we pulled out. Maalim vied for an MCA in the last election. Jessica thinks speech counts for this person should be posted under Eng. Maalim Mohamud Mohamed, the MP for Mandera West.

Margaret Nabwala Toili - She isn't a Member of Parliament but she also has speech counts. She vied for Kabuchai costituency Member of Parliament in the last election. her speech counts should just be deleted from the data.

**Comment by mhl** [comment]
To avoid this happening, @lizconlan  made a change in August last year
to exclude aspirants who are marked hidden from the name
matching: https://github.com/mysociety/pombola/commit/79d7f2

(We marked people as hidden when they were only an aspirant, and
hadn't got any other "interesting" positions: https://github.com/mysociety/pombola/blob/master/pombola/kenya/management/commands/kenya_hide_people.py )

These are the only two such cases in 2015:

```
In [13]: set(e.speaker for e in Entry.objects.filter(speaker__hidden=True, sitting__start_date__gte='2015-01-01'))
Out[13]: {<Person: Margaret Nabwala Toili>, <Person: Maalim Mohamed Abdisalan>}
```

Before 2015 there are a few more:

```
In [15]: set(e.speaker for e in Entry.objects.filter(speaker__hidden=True, sitting__start_date__lt='2015-01-01'))
Out[15]: 
{<Person: Monicah Wangare Gitau>,
 <Person: Charles Mwangi Waituru>,
 <Person: Nahashon Opiyo Ogutu>,
 <Person: Bonface Alouch Apopa>,
 <Person: George Omari Nyamweya>,
 <Person: Abraham Kiptanui>,
 <Person: Margaret Nabwala Toili>,
 <Person: James Mwangi Gakuya>,
 <Person: Godana Doyo Adhi>,
 <Person: Betty Njeri Tett>,
 <Person: Esther Keino>}
```

My thought was that we could fix this with:

```python
  for e in Entry.objects.filter(speaker__hidden=True):
     e.speaker = None
     e.save()
```

(n.b. using update on the queryset would bypass the signals that
Haystack needs to update Elasticsearch) ... and then running:

    ./manage.py hansard_assign_speakers

But this reassigns hidden people to most of those entries. That turns out to be because there are still `Alias` objects redirecting the names to those `Person` objects, so we have to remove them too:

```
In [11]: Alias.objects.filter(person__hidden=True)
Out[11]: [<Alias: Dr. Keino (aka Esther Keino)>, <Alias: Hon. (Eng. ) Mahamud (aka Maalim Mohamed Abdisalan)>, <Alias: Hon. Gakuya; (aka James Mwangi Gakuya)>, <Alias: Mr. GeorgeNyamweya (aka George Omari Nyamweya)>, <Alias: Mr. George Nyamweya (aka George Omari Nyamweya)>, <Alias: Mr. G. Nyamweya (aka George Omari Nyamweya)>, <Alias: Mr. G. O. Nyamweya (aka George Omari Nyamweya)>, <Alias: Mr. Kipatanui (aka Abraham Kiptanui)>, <Alias: Mrs. Tett (aka Betty Tett)>]
```

... with:

```python
for a in Alias.objects.filter(person__hidden=True):
    a.delete()
```

I've created a pull request which should stop you from being able to create aliases to hidden people in the admin interface: https://github.com/mysociety/pombola/pull/1933
