### ISSUE TITLE
Mzalendo - party page, suspect outdated

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#2008]
I suspect that the copy from [this page](http://info.mzalendo.com/info/political-parties) is as I wrote it back in 2012

![screenshot 2016-02-24 10 54 43](https://cloud.githubusercontent.com/assets/909811/13283312/1af0016a-dae5-11e5-9795-863b0959c0b4.png)

**Comment by tmtmtmtm** [comment]
Is there value in even having a page like this? Would we not be better with a page that lists all the parties (probably limited initially to those who have current representatives, but with the ability to expand to all parties), and ensure that the parties' own pages properly contain this sort of content? (i.e. resolving things like https://github.com/mysociety/pombola/issues/1940)

**Comment by tmtmtmtm** [comment]
How do you even get to that page? The link in the header bar to Political Parties goes to http://info.mzalendo.com/organisation/is/party/, which in turn lets you go to the individual party pages, where this text should be living. (Though we also need to resolve things like https://github.com/mysociety/pombola/issues/1940 for that to work better)

The party list page could certainly be improved though… probably by ordering by the number of active memberships, including party logos (similar to https://github.com/mysociety/pombola/issues/2003), etc

**Comment by tmtmtmtm** [comment]
Ah, that's the "Political Parties" link under "Parliament". I'd be inclined to just remove that in favour of the one under "National Assembly" (though it's unclear why there isn't a similar one under "Senate")

**Comment by tmtmtmtm** [comment]
Steps:

1. [ ] Ensure that all of the parties on http://info.mzalendo.com/info/political-parties already have a suitable blurb; otherwise cope the blurb from here
2. [ ] Delete the /info/political-parties page and redirect to /organisation/is/party/
3. [ ] Remove the link from the header bar

For the header bar; is it trivial to have a view of /organisation/is/party that is restricted to parties who have members in that legislature? If so we should have individual links under the Assembly and Senate drop-downs to pages tailored for them. If not, we should change the link under Parliament to go to '/organisation/is/party/', and remove the link from the NA dropdown (as the coalitions are the primary element anyway).  [By trivial here, I mean a link that we can already construct with the code as-is; non-trivial means adding any new code]

**Comment by duncanparkes** [comment]
Tony - in answer to your question, not hard, but not that trivial. Would require a new view, I think.

**Comment by duncanparkes** [comment]
Only remaining thing, once #2035 is deployed, is to remove the old info page (and actually, it's mostly harmless as it can't be reached).

**Comment by duncanparkes** [comment]
#2035 has been rebased and merged. Now just need to remove the old info page using the Django admin.

**Comment by tmtmtmtm** [comment]
Done in admin.
