### ISSUE TITLE
[ZA] Make "Ward Councillor" link more prominent on Ward Rep Locator page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2106]
For the mockup Zarino did for People's Assembly, they want the Ward Councillor link to be more prominent

![screen shot 2016-03-10 at 09 49 49](https://cloud.githubusercontent.com/assets/4170351/13665703/a891765e-e6a5-11e5-952a-ddb008d80fd1.png)

**Comment by zarino** [comment]
Now that there are 3 tabs (MPs, MPLs, Councillor) I think this is less of a problem. Megan didn't mention it in her most recent round of feedback (22 March).

If we find out it really is still an issue, my suggestion would be to show people their Councillor *first*, rather than landing on the MPs first.
