### ISSUE TITLE
Lack of posts on Kipruto Moi's profile

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#2128]
@JenMysoc @duncanparkes 

Please check where the problem could be, Hon. Kipruto's Moi contributions in the National Assembly have always been allocated to his brother Sen. Gideon Moi. 
Below are their profiles:

1.http://info.mzalendo.com/person/kipruto-moi/
2. http://info.mzalendo.com/person/gideon-moi/

They are both former President Moi's sons.

**Comment by tmtmtmtm** [comment]
All the appearances on http://info.mzalendo.com/hansard/person/gideon-moi/appearances/ that are for the Assembly should almost certainly not be there — but should be for Kipruto Moi instead.

I had a look at http://info.mzalendo.com/hansard/sitting/national_assembly/2016-03-02-14-30-00#entry-627694 — in the underlying source he's listed as "Hon. Moi" which presumably is enough for us to differentiate, but my suspicion is that we're just picking up the "Moi" and finding the wrong person.

**Comment by mhl** [comment]
The problem here was that there was an alias on the website (created in December 2013 by Jessica) from "Hon. Moi" to Gideon Moi. I've changed that alias (which is only used in the National Assembly, so I think all should refer to Kipruto Moi), removed the old assignments with:

```
In [4]: for e in Entry.objects.filter(speaker_name='Hon. Moi'):
    e.speaker = None
    e.save()
```

... and reassigned them with:

```
./manage.py hansard_assign_speakers
```

The appearances are now on http://info.mzalendo.com/person/kipruto-moi/
