### ISSUE TITLE
[ZA] Level of detail in location needed to return different categories of Reps is confusing

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2155]
PMG are having trouble getting people to understand the information they need people to input into the rep locator form on the homepage to return results for the different types of representatives. 

For a ward representative you need to enter in your street address to get the *correct* representative for your ward. 

For an MP or MPL you need to enter a wider location, like an area of a city (for example Redland, Bristol) to ensure you return the right results. 

PMG have suggested that we should present three separate rep locators with clear instructions on how to find the locator. @zarino do you have any other ideas about this? It sounds like a place where design wonderment might help!

**Comment by mhl** [comment]
It seems that the issue here is only when people put in too generic a location into that box; the results when they put in a street address is actually fine. So, we've changed the placeholder text to ask for an "address" not a "location" - hopefully this will be enough to reduce the confusion.

Further steps we could take include detecting when a wide area is resolved by geocoding and either including multiple wards that might overlap, or just warning that the results won't be precise. But for the moment, we'll see if this change is enough from feedback from PMG.
