### ISSUE TITLE
[ZA] Change where the newsletter icon and subscribe link goes to

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2186]
PMG have asked if we could change where the subscribe link in the footer of the site and the yellow newsletter icon in both the header and footer go to.

![screen shot 2016-08-01 at 09 03 37](https://cloud.githubusercontent.com/assets/4170351/17291695/67020d76-57dd-11e6-83fa-43c46995b656.png)

The new link is https://mail4.marketingautomation.services/prospector/form/MzawMDE2MrUwBwA/SzMyMjE3NErSNTAzSdI1SbFI07VITLTQTTZJM05NSjOzNEy1AAA

The newsletter page subscribe link on http://www.pa.org.za/info/newsletter should also be changed to go to this new link although the link to this newsletter page has been removed from the site. 

![screen shot 2016-08-01 at 11 46 36](https://cloud.githubusercontent.com/assets/4170351/17291758/b1bd1914-57dd-11e6-8e3b-04c53e313661.png)

**Comment by zarino** [comment]
The signup form, on its own, looks pretty uninviting:

![screen shot 2016-08-01 at 11 49 01](https://cloud.githubusercontent.com/assets/739624/17291818/0400ee30-57de-11e6-8ba5-abbe336f5aef.png)

Makes me wonder whether:

1. The signup form can be customised? (we can't customise it, since it's not hosted by us, but PMG might have customisation options via their own admin panel?)
2. We should embed the form in an `iframe` inside a page we *do* host?

Looks like PMG also provided a javascript snippet we could use, to embed the form in our own pages, client-side. I've not tried it out yet, but that could be another alternative. We'd just need to work out where the form should be embedded. (eg: http://www.pa.org.za/info/newsletter would have been a sensible page to put the form on, were it not currently full of "MONITOR" stuff)

**Comment by mhl** [comment]
The Javascript snippet just embeds the whole of that form - after tweaking in developer tools to make the labels visible, that would look like this:

![pictures-injected-form](https://cloud.githubusercontent.com/assets/7907/17438289/f2afaa06-5b19-11e6-8195-d8bab8e00f8a.png)

... which is a bit silly. Some options:

* It looks as if the form has the same action and parameter names each time, so we could include a similar form but with placeholder values for everything except email address. This means that the form might break (and without us noticing) if the marketing company change their backend at any point. Also, PMG might actively want first name, last name and company details. (I wouldn't ask for these myself, in the interests of making it as easy as possible to sign up.)
* As Zarino says, they can see if they can customize the form via the marketing service's control panel, or whatever.
* Just leave out the the "single email address box" from the footer. It seems like a nice thing to have to me, though. We don't have data on how much it's used, but I bet that gets more use than clicking through to another page first.

**Comment by zarino** [comment]
@mhl – Another option:

* After the form is inserted with javascript, find the "email" input and its associated label, and move it to the top of the form. Then, hide the other inputs. Slide the other inputs into view when the email input is focussed. 

We could also use either CSS or javascript to remove the "Subscribe to the People’s Assembly Newsletter" form title, since that part of the footer already has a small "SIGN UP TO OUR MAILING LIST" heading.

**Comment by mhl** [comment]
@zarino: The JavaScript snippet for embedding the form inserts an iframe which is sourced from another domain, so I don't think we can change the contents of it with JavaScript (but I'd have to double-check that).

**Comment by zarino** [comment]
@mhl: Oh! Nasty iframes.

**Comment by JenMysoc** [comment]
@mhl @zarino the js snippet has been edited to only require the email now which might solve a lot of the problems?

**Comment by mhl** [comment]
@JenMysoc That helps in that we don't have to make up the other fields when submitting from the footer. The problem with using the JavaScript snippet at all, though, is that we can't style the form.

What I've done in 286d6d9e9c0f3f995bc27 (part of this PR: https://github.com/mysociety/pombola/pull/2191)  is to replicate the form you get from including the snippet with the same styling as previously. That does mean it might stop working if that form changes, but I can't see a better way around it. What do you think, @zarino?

**Comment by zarino** [comment]
@mhl https://github.com/mysociety/pombola/commit/286d6d9e9c0f3f995bc2756528f2ba0004f1264d is exactly what I would have done.

The only other way I could imagine doing it, would be to ajax in the [content of their form](https://mail4.marketingautomation.services/prospector/form/MzawMDE2MrUwBwA/SzMyMjE3NErSNTAzSdI1SbFI07VITLTQTTZJM05NSjOzNEy1AAA) and pull out the fields we want – but they don't set an `Access-Control-Allow-Origin` header, so the ajax request fails. You could proxy it, or get the django server to scrape the form and inject the content into the template, but at that point we're really getting quite silly.

**Comment by JenMysoc** [comment]
Ok if that looks right to you both I say 👍  :)
