### ISSUE TITLE
[KE] New logo for Mzalendo

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2205]
![mzalendo-banner-logo](https://cloud.githubusercontent.com/assets/4170351/19233493/aac8e46c-8edd-11e6-83d4-9c8bbb13a95c.png)

This logo should be used as the logo in the header for the whole of the Mzalendo site.

Be aware that the blog page (http://www.mzalendo.com/blog/) is coming in from wordpress incase that causes similar issues to the recent menu fold ones (#2200)

**Comment by JenMysoc** [comment]
As a starting point, could we mock up how it will look and share it - as the current site header is fully green which might make this green and black ended logo look strange. If we can show this as it stands and give jessica the option to change either the whole header or nothing that would be great!

**Comment by zarino** [comment]
@JenMysoc Do you have an original (vector) version of the logo? Like an Illustrator file (.AI), a PDF, an EPS, or an SVG?

**Comment by JenMysoc** [comment]
ooo I don't but I can ask Jess now :)

**Comment by zarino** [comment]
As a reminder, here’s what it looks like currently:

![original](https://cloud.githubusercontent.com/assets/739624/19265799/97840ea6-8f9e-11e6-9977-c5463f43da79.jpg)

We have a few options available to us:

**A** – just update to the new "MZALENDO" text (it's in a slightly different font now, and slightly smaller in comparison with the shield) and the new darker green:

![a](https://cloud.githubusercontent.com/assets/739624/19265808/b04ea0c2-8f9e-11e6-8162-99086da7064a.jpg)

**B** – incorporate the black and green "wedges" – but at the far left and right ends of the header:

![b](https://cloud.githubusercontent.com/assets/739624/19265821/c3e3969c-8f9e-11e6-83c9-d9a7b275405e.jpg)

**C** – bring those wedges in a bit, to make more of a feature out of them:

![c](https://cloud.githubusercontent.com/assets/739624/19265823/d17616cc-8f9e-11e6-836f-643f8fc848ce.jpg)

**D** – bring the wedges *all the way* in, essentially displaying the logo exactly as supplied:

![d](https://cloud.githubusercontent.com/assets/739624/19265835/e3f5b6b8-8f9e-11e6-97ed-76a1c500db7c.jpg)

(It's worth clicking on the images to see them at 100% scale, otherwise you don't really get a true feel for how they’ll look in real life.)

@JessMusila @wrightmartin what do you think?

**Comment by JessMusila** [comment]
Hi @zarino @JenMysoc @wrightmartin 

We love option C.

Regards,

Jessica

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/pombola/pull/2207
