### ISSUE TITLE
[KE] Senate members showing 2020 date for most recent speeches

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2210]
Jessica has alerted us that all of the senate members who have spoken recently have a 2020 date for their recent speeches.

![screen shot 2016-11-10 at 17 12 10](https://cloud.githubusercontent.com/assets/4170351/20186690/dd2f68f6-a768-11e6-90ce-da82e5458209.png)

The Senate debate that's come into the list has shown up with this URL: http://info.mzalendo.com/hansard/sitting/senate/2020-10-04-14-30-00 and on the Hansard page it is showing up with 2020 as the date, 

![screen shot 2016-11-10 at 16 57 07](https://cloud.githubusercontent.com/assets/4170351/20186540/5bb75eaa-a768-11e6-99ef-c923c96f189f.png)

though within the Hansard record itself it shows the right date within the text of the hansard. It is showing some strange dates at the top of the hansard and on the page 1 link.

![screen shot 2016-11-10 at 17 09 10](https://cloud.githubusercontent.com/assets/4170351/20186605/928f35b0-a768-11e6-934c-69c53b7d5aae.png)
 
I've checked the Hansard page on the government website (http://www.parliament.go.ke/the-senate/house-business/hansard) and it looks like everything is fine there.

![screen shot 2016-11-10 at 17 11 16](https://cloud.githubusercontent.com/assets/4170351/20186647/bb80120a-a768-11e6-858c-9c3917092310.png)

**Comment by mhl** [comment]
@octopusinvitro and I have investigate this and here's what seems to have happened:

For a brief period, there was a link on that page to the 4th of October's senate sitting, but which had the wrong date listed on it - it was listed with a year of "201" instead of "2016". The date parsing library that we used got confused by this date from the third century and interpreted it as "2020". You can see the year 201 in your screenshot, in fact:

![year-201](https://cloud.githubusercontent.com/assets/7907/20628738/af354c46-b31f-11e6-86dc-6bec8269554c.png)

Later they fixed the date and uploaded a new file, which our scraper also picked up. This means that all those speeches and appearances appeared twice - once for a sitting in 2016 and once for one in 2020.

This means that it is safe to remove the erroneous 2020 source, and it won't have lost any speeches. We've done that now, so the appearances on those profiles are now fixed, e.g.:

![lesan-fixed](https://cloud.githubusercontent.com/assets/7907/20628668/47fc595c-b31f-11e6-8a4a-ff7b0b656b7d.png)
