### ISSUE TITLE
[ZA] Create "must read" section on RHS menu on blog page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2213]
![screen shot 2016-11-18 at 11 23 20](https://cloud.githubusercontent.com/assets/4170351/20428811/fd26ac12-ad82-11e6-9857-a90b62b6530e.png)

Currently the Blog page RHS menu on PA has two sections; Recent Posts and Popular Posts. PMG have indicated that underneath this section they would like a "Must read" section which links out to blogs they have decided are "must read" blogs.

Ideally, to indicate that a blog entry is "Must Read" PMG would be able to do something like add a tag, or tick a box, to add a blog to the must read section. 

They want to have up to 4 blogs in this section at a time - so we may need to find a way that they can easily find all blogs selected as must read in the admin section - so they can easily deselect ones that have been on there for a while. 

We need more feedback from them on the following things:
- Whether they want the "must read" section to be a section in itself on the main menu dropdown from the blog section
- Whether they expect to remove blog posts from this section a regular basis or if they just expect to only show the most recently added "must read" blogs

**Comment by mhl** [comment]
@JenMysoc We (@octopusinvitro and I) have deployed some changes so that they can have the "Must Read" section now. We've created a "Must Read" tag, so they just need to find the posts they want in that section in the admin and add that tag - then those posts should appear in the sidebar.

![must-read](https://cloud.githubusercontent.com/assets/7907/20605613/420e831e-b264-11e6-8542-36ed994c7297.png)
