### ISSUE TITLE
[ZA] Increase visibility of the name search box on MP Profiles page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2216]
PMG had overlooked the work we did on the search box on the MP profiles page and were also unaware that the box allowed you to start typing and the word would autocomplete. 

![screen shot 2016-11-21 at 12 49 03](https://cloud.githubusercontent.com/assets/4170351/20518663/d9e81f8e-b097-11e6-8f7e-aedebb5a3476.png)

Above is the search box on the page as it currently looks. Can a designer think of a way to make this more visible and eye catching to a user? http://www.pa.org.za/position/member/parliament/?order=name

**Comment by zarino** [comment]
Makes sense that it should be styled like the search box on the Search Results page – especially since, when you submit your search term, you’re taking to that Search Results page anyway.

![screen shot 2016-11-22 at 09 49 54](https://cloud.githubusercontent.com/assets/739624/20519015/2b656910-b099-11e6-8404-1097731f6502.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/pombola/pull/2218
