### ISSUE TITLE
[KE] Word clouds for MP pages

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2235]
Jessica has brought up the age old question of "word clouds" for MP pages showing the topics they're speaking about most based on the hansard report we run for her. 

Is there a better way to generate and display this type of information on a month by month basis - crucially that we wouldn't need to do much work for each month? @zarino and @wrightmartin may know of some things!

**Comment by zarino** [comment]
A few thoughts after looking into this quickly this morning:

* There are a handful of really quite good client-side javascript word cloud generators – like [d3-cloud](https://github.com/jasondavies/d3-cloud) (SVG output, using D3 and Canvas) and [wordcloud2.js](https://github.com/timdream/wordcloud2.js) (Canvas output).
* **BUT** Opera Mini (46% of sessions on Mzalendo) has really poor Canvas support – both [d3-cloud](https://github.com/jasondavies/d3-cloud) and [wordcloud2.js](https://github.com/timdream/wordcloud2.js) fail to render in it.
* Which makes me wonder whether we should render the SVG server-side, and then send it to the client as a static image?

And about word clouds in general:

* The key problem with word clouds is that they attempt to communicate the prevalence of a word by varying its size, but they generally don't compensate for the already existing size differences of words. Eg: Even if the words "parliament" and "war" were mentioned the same number of times, and are thus rendered in the same font-size in the word cloud, "parliament" will still appear to be visually bigger, because it's a longer word.
* A secondary problem is that there’s a lot of noise for very little signal. It’s almost always better to single out a few key words, and present bar graphs / frequency graphs of those alone, than to dump everything into a cloud and expect the *reader* to analyse it themselves.
* Finally, they’re not great for showing changes over time – which is a use-case Mzalendo, with their historical records, could really capitalise on. If we generate a word cloud per year, unless we’re very careful, the words will jump around randomly year to year, making year-to-year comparisons difficult. It would be much easier to pick out a few key words, and track their use over time, as simple frequency graphs.
* They *are*, however, visually interesting. :-/

**Comment by zarino** [comment]
@JenMysoc should this ticket be closed in favour of https://github.com/mysociety/pombola/issues/2260 ?

**Comment by JenMysoc** [comment]
Yep!
