### ISSUE TITLE
ZA: add GA tracking of whether people use the filter box on the MP profiles page

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2259]
As suggested by @zarino we should really find out whether people are using this box:

![screenshot from 2017-03-24 18-27-25](https://cloud.githubusercontent.com/assets/7907/24308388/adf72ab8-10bf-11e7-9a2d-fa3e1a372533.png)

on http://www.pa.org.za/position/member/parliament/ by tracking input events in Google Analytics

**Comment by jacksonj04** [comment]
This is actually more complex than initially seeming, and there's a bit of a brain dump going on here:

* This search is all done in JS, which is absolutely fine because GA reports using JS, except:
* It also uses [Fuse.js](http://fusejs.io/) to do fuzzy searching locally. Everything is nicely tied into functions, so we can just do reporting in there rather than watching for our own events, except:
* It performs a full search on every keystroke, including the first one.
* Reporting back on every keystroke of a search is stupid. So, we could:
  * Pop the GA report in a latch, so it only happens once, and just report that a search happened and not what the search was for.
  * Introduce a 'person is typing' delay to the _entire_ search, which may make results filtering seem more laggy, but makes it more sensible to try and send the search contents.
  * Put the reporting in its own separate function and report on it every time the typing has stopped for what could be considered a 'reasonable' amount of time.

Of these, the final option of leaving search alone entirely and having a separate function to track when typing stops for the purpose of reporting makes most sense.

**Comment by zarino** [comment]
When I mentioned this to @markl, it was in the context of _just knowing whether search is used at all_ on this page, or whether the majority of people just scroll down the list manually.

So, firing a Google Analytics event on the first `keypress` inside the search `<input>` would be fine. (Don’t want `keydown`, `keyup`, `focus`, or `blur` as they could get triggered even if a person is just tabbing through all the elements on the page.)

Unless you have a hypothesis in mind that would require knowing _exactly_ what people are typing into the search box?

**Comment by jacksonj04** [comment]
If we only care if it's used, I'll just do a straight latching report.
