### ISSUE TITLE
admins not getting notifications for new comments using the Facebook widget

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2281]
This was reported by @xybrnet:

> We've received an enquiry from [...] at People's Assembly, where she said that she's not receiving notifications for comments made on the PA site.

This might be to do with the Facebook app that we're using to record comments not being marked as "live", but this needs more investigation.

**Comment by chrismytton** [comment]
There don't seem to be any comments appearing in the [comment moderation tool](https://developers.facebook.com/tools/comments/1619725741628189/pending/descending/). After a bit of digging it seems that this is because we need to add a `<meta property="fb:app_id" …>` tag, which is documented in the [comment moderation setup instructions](https://developers.facebook.com/docs/plugins/comments#moderation-setup-instructions).

**Comment by chrismytton** [comment]
Additionally, [this Stack Overflow post](https://stackoverflow.com/a/34252960) suggests that once we've got the moderation tool working we'll need to go into the comment moderation tool settings and add People's Assembly as a "moderator" (and possibly remove them as an admin on the app).

**Comment by chrismytton** [comment]
Also as @mhl notes in the original comment text, the app wasn't yet live. I've now toggled the switch in the app settings to make it live.

**Comment by chrismytton** [comment]
I added the `fb:app_id` meta tag in https://github.com/mysociety/pombola/pull/2283 but it's still not being output on blog posts.

I did a bit more digging and found that [`pombola/south_africa/templates/info/blog_post.html#L17`](https://github.com/mysociety/pombola/blob/4d05dc88f3be6acfddc49b18cf4ccff907720557/pombola/south_africa/templates/info/blog_post.html#L17) overrides the open graph block and includes [this template](https://github.com/mysociety/django-info-pages/blob/2d6159090a61862ff5a6459c61678e68b9c66fe5/info/templates/info/_blog_open_graph.html) from django-info-pages.

So I think the best thing to do is to move the `fb:app_id` meta tag outside the `open_graph` template block so that it is _always_ in the HTML output.

**Comment by chrismytton** [comment]
The `fb:app_id` meta tag is appearing on every page now https://github.com/mysociety/pombola/pull/2285 has been merged.

I still wasn't seeing any comments in [Facebook's comment moderation tool](https://developers.facebook.com/tools/comments/) though, so I used Facebook's [sharing debugger](https://developers.facebook.com/tools/debug/sharing/) to fetch [this page](http://www.pa.org.za/blog/mr-zondi-makhubele) and then clicked the "Scrape Again" button to force a re-fetch. Once I'd done that the comments for that page appeared in the comment moderation tool. :tada:

The [page about Facebook's crawler](https://developers.facebook.com/docs/sharing/webmasters/crawler) doesn't indicate how often pages are re-scraped, but a random sampling showed most pages are scraped at least every 24 hours, I guess more frequently visited ones will be scraped more often. So once the pages with comments on have been re-scraped the comments will appear in the comment moderation tool.

**Comment by chrismytton** [comment]
Once comments are appearing in the tool there's one final action before this ticket can be closed:

- [ ] Add our PA contact (who is currently listed as an admin on the [Facebook app](https://developers.facebook.com/apps/1619725741628189/roles/)) as a "moderator", which can be done on the "Settings" screen of [Facebook's comment moderation tool](https://developers.facebook.com/tools/comments/).

**Comment by chrismytton** [comment]
We can't seem to be able to add other people as moderators, so we've emailed PA with instructions on how to add themselves as a moderator.

**Comment by mhl** [comment]
They've done that now, so hopefully that's all that's needed :) Thanks, @chrismytton
