### ISSUE TITLE
[ZA] Design to integrate the writing to committees into PA

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2382]
We're at the point where we need to think about the design for integrating the WiP for Committees into People's Assembly. This should look relatively similar to the writing to MPs site.

People need to be able to:
- Follow button from homepage to a page that gives them a dropdown list of committees and a text box to write in.
- Clicking on submit should show them a page (I believe - @chrismytton can confirm) where they can preview their message before sending, and then click send
- Submitting should show them a message saying their message will be moderated and link them to the main homepage

There also needs to be a page for all the public messages to committees, and it would be good if this is separated or searchable in some way by committee - however I think this will depend on what @chrismytton has done for that part of the build :)

**Comment by chrismytton** [comment]
I think the bullet points above are actually all already done, because the committee writing wizard has inherited the code and styles from the Write to an MP version. So the outstanding bits that I think need doing are:

### Links on individual committee page

- [ ] I’ve added two links to http://za-pombola.staging.mysociety.org/organisation/cooperative-governance-and-traditional-affairs/, one linking to messages sent to a committee and one to write to a particular committee (which just skips the “choose a recipient” step of the wizard), would be good to make them fit in with this page.

I've added the code for those links here:

https://github.com/mysociety/pombola/blob/9534911ba80a6a46ff480be185d5890cfebba3b0/pombola/south_africa/templates/core/organisation_detail.html#L39-L47

### Messages sent to a committee

- [ ] When you click that “Public messages” link you are taken to http://za-pombola.staging.mysociety.org/organisation/cooperative-governance-and-traditional-affairs/messages/, which is a list of messages sent to a particular committee. This page might need a bit of design love.

The code for that page is here:

https://github.com/mysociety/pombola/blob/9534911ba80a6a46ff480be185d5890cfebba3b0/pombola/south_africa/templates/writeinpublic/committee-messages.html#L7-L19

---

I'm open to suggestions of better ways to display the committee messages and link things up! Give me a shout if you have any questions about anything 📣

**Comment by JenMysoc** [comment]
I think this is done now?

**Comment by chrismytton** [comment]
> I think this is done now?

It totes is!
