### ISSUE TITLE
[KE] Homepage design refresh for Mzalendo

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2421]
Jessica would like a homepage/general redesign for Mzalendo. She's had some feedback from other CSOs in Kenya that the website doesn't communicate well what they do and thus it's hard for her to get funding for the things that are important or that she'd like to make important.

Current homepage is quite busy:

![screen shot 2018-05-09 at 12 33 45](https://user-images.githubusercontent.com/4170351/39812614-46afd10c-5385-11e8-9b66-fbef7f418492.png)

She will send us some examples of pages that she thinks look good and a list of items that need to be on the homepage but in general:

* Women parliamentarians have expressed an interest in being more involved and more prominent on Mzalendo - and Jessica is keen to have a focus on both women and youth as they've done research into these subsets of parliamentarians. 

* CSOs that use the site want committee hansards and more committee involvement; this is an area where Jessica thinks she could apply or push for funding, especially where it intersects with bills and thus she could leverage Dokeza more. A possible suggestion is for her to look at PMG's work with committees and bills with their WiP and surveys and see if there's anything that would work for her.

* Jessica wants to encourage more engagement with the site through social media (bringing twitter up to a more prominent position maybe and having shortcode polls on the site as well)

* ~Jessica would like to run some user research via a survey on the site to get an idea of what people want to see more/less of (maybe @zarino @wrightmartin @ajparsons would have some ideas on what/how to do this?)~ – Survey broken out into #2446

**Comment by zarino** [comment]
More feedback about this from last week‘s call with Jessica and Abiud:

* They like the layout of peoples assembly homepage, with the clear horizontal sections. They cited pa.org.za as a goal to reach for – "There’s something about it that’s very clean."

* They want to include a plugin that displays "crawling comments" from people using the "Bonga-Na-Mzalendo" SMS shortcode. They have a new question every week or month, and then people send in their responses. Someone is building this plugin for them. They’ll follow up how it’ll work and get back to us. The shortcode has been really good for them – they’ve had messages from people in something like 35 of the 47 counties in Kenya, and over 50% were from women.

* 3 key things with equal importance on the homepage are: SMS shortcode, Dozeka, and Newsletter.

* Need a direct link to the Facebook page. Twitter, Facebook, Instagram and YouTube are really important, because the public uses photos and videos to discuss political issues.

**Comment by zarino** [comment]
For building the "crawling comments" plugin:

Sample GET URL Call:

```http://72.167.34.22/oliveAPIs/index.php/api/bulk/fetchLatestMessages/format/json?limit=3&short_code=21516```

(Adjust limit param to fetch the appropriate number of messages you want to retrieve.)

Sample JSON Response:

```json
{
    "status": 200,
    "status_message": "Fetched Messages For - 21516",
    "latest_messages": {
        "1": {
            "MSISDN": "254706638280",
            "message": "B",
            "time_in": "2017-10-05 20:30:36",
            "shortcode": "21516"
        },
        "2": {
            "MSISDN": "254706638280",
            "message": "B",
            "time_in": "2017-10-05 20:30:39",
            "shortcode": "21516"
        },
        "3": {
            "MSISDN": "254706638280",
            "message": "B",
            "time_in": "2017-10-05 20:30:46",
            "shortcode": "21516"
        }
    }
}
```

**Comment by zarino** [comment]
I‘ve created a new ticket for the back-end work that’ll need to go into the SMS storage / display: https://github.com/mysociety/pombola/issues/2462

**Comment by zarino** [comment]
Pull request here, not quite finished yet: https://github.com/mysociety/pombola/pull/2478

**Comment by zarino** [comment]
While @chrismytton works on #2266, the updated homepage (with hard-coded SMS messages) has been deployed to http://mzalendo.staging.mysociety.org.

The blog posts don’t load because of CORS restrictions (`www.mzalendo.com/feed` can only be loaded by pages at `info.mzalendo.com`) but if you disable CORS checking in your browser, you’ll see they work fine.
