### ISSUE TITLE
[ZA] Multiple active tabs on rep locator 

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2555]
From Megan:

> Results on the rep locator open on Ward Councillor by default, but this is not clear based on how the tabs highlight, e.g. if I put in my address (16 leinster road, green point), this is how the tabs look:
>
> ![image](https://user-images.githubusercontent.com/22996/52636816-8e290a00-2ec5-11e9-81d1-4b30569d477c.png)
>
> Is it possible that the tab that is live/being viewed can show as blue or **bold blue**?

**Comment by zarino** [comment]
Before we change any styling, we should first investigate the bug here – that both the first and second tabs are being given the `active` classes, and so are appearing grey, unclickable, and with the thicker border below them. Really, only the first item should be active.

Once we’ve fixed that, if the MPG team still think the "active" styling isn’t clear enough (it’s been like this for years, what’s changed?) then we’ll look at beefing it up across the whole site.

**Comment by zarino** [comment]
To address Megan’s question about link colours – we don’t use blue for links anywhere else on the site (apart from, admitedly, the footer, but that’s for contrast reasons) so it’d feel a bit inconsistent to suddenly use it here.

If the "selected" state of the tabs needs changing, then the least ambiguous way to do it would be with more traditional "tab" styling, eg: http://info.mzalendo.com/ui-test

<img width="474" alt="Screen Shot 2019-03-12 at 09 53 50" src="https://user-images.githubusercontent.com/739624/54190920-c4e64600-44ac-11e9-90b3-021943f196ec.png">

**Comment by chrismytton** [comment]
> Before we change any styling, we should first investigate the bug here – that both the first and second tabs are being given the `active` classes, and so are appearing grey, unclickable, and with the thicker border below them. Really, only the first item should be active.

Aha good spot, hadn't noticed that! Will investigate that, leave it with me.

**Comment by chrismytton** [comment]
Have fixed the active tab problem in #2577. If we need to do anything further with the active tab styles I'll open a new ticket for that.
